logging.level.au.edu.rmit.student.weiminsu.cosc2626.playtogether.mappers: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5422}/${RDS_DB_NAME:play-together}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:test}
    driverClassName: org.postgresql.Driver
    initialization-mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: au.edu.rmit.student.weiminsu.cosc2626.playtogether.mappers
