/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package au.edu.rmit.student.weiminsu.cosc2626.playtogether;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
    }
}
